# Generated by Django 4.2.17 on 2024-12-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                help_text="Укажите описание курса", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку",
                null=True,
                upload_to="course_previews/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Укажите название курса",
                max_length=200,
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                help_text="Укажите описание урока", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку",
                null=True,
                upload_to="lesson_previews/",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                help_text="Укажите назыание урока",
                max_length=200,
                verbose_name="Название урока",
            ),
        ),
    ]
